# Generated by Django 3.1.3 on 2022-11-04 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamTitle', models.CharField(default='unassigned', max_length=255, unique=True)),
            ],
            options={
                'db_table': 'team',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('hourlyRate', models.FloatField()),
                ('teamAffiliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.team')),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
