# Generated by Django 3.1.3 on 2022-11-04 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_workarrangement'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employees.team')),
            ],
            options={
                'db_table': 'teamMember',
            },
        ),
        migrations.CreateModel(
            name='TeamLeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employees.team')),
            ],
            options={
                'db_table': 'teamLeader',
            },
        ),
    ]
