# Generated by Django 3.1.3 on 2022-10-29 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Hourly_Rate', models.FloatField()),
            ],
            options={
                'db_table': 'Employee',
            },
        ),
    ]
