# Generated by Django 3.1.3 on 2022-10-30 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplusplusapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Team_Affiliation',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterModelTable(
            name='employee',
            table='employee',
        ),
    ]
