# Generated by Django 3.1.3 on 2022-11-01 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplusplusapp', '0002_auto_20221030_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('teamTitle', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TeamEmployee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member', to='aplusplusapp.employee')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplusplusapp.team')),
            ],
        ),
        migrations.CreateModel(
            name='WorkArrangement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('workTitle', models.CharField(max_length=255)),
                ('workedTime', models.CharField(choices=[('Full Time', 'Ft'), ('Part Time', 'Pt'), ('Part Time 75%', 'Pt75'), ('Part Time 50%', 'Pt50'), ('Part Time 25%', 'Pt25')], max_length=255)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_by_employee', to='aplusplusapp.teamemployee')),
            ],
        ),
        migrations.CreateModel(
            name='TeamLeader',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leader', to='aplusplusapp.employee')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplusplusapp.team')),
            ],
        ),
    ]
