# Generated by Django 3.1.3 on 2022-11-01 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplusplusapp', '0003_team_teamemployee_teamleader_workarrangement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workarrangement',
            name='workedTime',
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('workedTime', models.CharField(choices=[('Full Time', 'Ft'), ('Part Time', 'Pt'), ('Part Time 75%', 'Pt75'), ('Part Time 50%', 'Pt50'), ('Part Time 25%', 'Pt25')], max_length=255)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member', to='aplusplusapp.employee')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplusplusapp.team')),
            ],
        ),
        migrations.AlterField(
            model_name='workarrangement',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_by_employee', to='aplusplusapp.teammember'),
        ),
        migrations.DeleteModel(
            name='TeamEmployee',
        ),
    ]
