# Generated by Django 3.1.3 on 2022-11-02 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplusplusapp', '0004_auto_20221101_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workarrangement',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_by_employee', to='aplusplusapp.employee'),
        ),
    ]
