# Generated by Django 3.1.3 on 2022-11-02 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplusplusapp', '0005_auto_20221102_0915'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='workarrangement',
            table='WorkArrangement',
        ),
    ]
