# Generated by Django 3.1.3 on 2022-11-03 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplusplusapp', '0006_auto_20221102_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workarrangement',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
