# Generated by Django 3.1.3 on 2022-11-04 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplusplusapp', '0007_auto_20221103_0745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Hourly_Rate',
            new_name='hourlyRate',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='Team_Affiliation',
            new_name='teamAffiliation',
        ),
        migrations.AlterField(
            model_name='workarrangement',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='aplusplusapp.employee'),
        ),
    ]
