# Generated by Django 3.1.3 on 2022-11-04 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplusplusapp', '0008_auto_20221104_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
