# Generated by Django 3.1.3 on 2022-11-04 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplusplusapp', '0009_auto_20221104_0208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='workedTime',
        ),
        migrations.AddField(
            model_name='workarrangement',
            name='workedTime',
            field=models.CharField(choices=[('Full Time', 'Ft'), ('Part Time', 'Pt'), ('Part Time 75%', 'Pt75'), ('Part Time 50%', 'Pt50'), ('Part Time 25%', 'Pt25')], default='Full Time', max_length=255),
        ),
    ]
