# Generated by Django 3.1.3 on 2022-11-04 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplusplusapp', '0010_auto_20221104_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workarrangement',
            name='workedTime',
            field=models.CharField(choices=[('Full Time', 'Ft'), ('Part Time 100%', 'Pt'), ('Part Time 75%', 'Pt75'), ('Part Time 50%', 'Pt50'), ('Part Time 25%', 'Pt25')], default='Full Time', max_length=255),
        ),
    ]
