# Generated by Django 3.1.3 on 2022-11-04 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplusplusapp', '0011_auto_20221104_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workarrangement',
            name='workedTime',
            field=models.CharField(choices=[('FT', 'Full Time'), ('PT', 'Part Time 100%'), ('PT75', 'Part Time 75%'), ('PT50', 'Part Time 50%'), ('PT25', 'Part Time 25%')], default='Full Time', max_length=255),
        ),
    ]
