# Generated by Django 3.1.3 on 2022-11-04 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplusplusapp', '0013_auto_20221104_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamleader',
            name='leader',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leader', to='aplusplusapp.employee', to_field='name'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member', to='aplusplusapp.employee', to_field='name'),
        ),
    ]
