# Generated by Django 3.1.3 on 2022-11-04 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplusplusapp', '0014_auto_20221104_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='teamAffiliation',
            field=models.OneToOneField(default='unassigned', on_delete=django.db.models.deletion.CASCADE, related_name='teamAffiliation', to='aplusplusapp.team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='teamTitle',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
