# Generated by Django 3.1.3 on 2022-11-04 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplusplusapp', '0015_auto_20221104_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='teamAffiliation',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='teamAffiliation', to='aplusplusapp.team'),
        ),
    ]
