# Generated by Django 3.1.3 on 2022-11-04 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplusplusapp', '0016_auto_20221104_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='teamAffiliation',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='belongsTo', to='aplusplusapp.team'),
        ),
    ]
