# Generated by Django 3.1.3 on 2022-11-04 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplusplusapp', '0017_auto_20221104_1056'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='team',
            table='team',
        ),
    ]
