# Generated by Django 3.1.3 on 2022-11-04 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplusplusapp', '0018_auto_20221104_1104'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='teamleader',
            table='teamLeader',
        ),
        migrations.AlterModelTable(
            name='teammember',
            table='teamMember',
        ),
        migrations.AlterModelTable(
            name='workarrangement',
            table='workArrangement',
        ),
    ]
