# Generated by Django 3.1.3 on 2022-11-04 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplusplusapp', '0019_auto_20221104_1105'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='Employee',
        ),
        migrations.AlterModelTable(
            name='team',
            table='Team',
        ),
        migrations.AlterModelTable(
            name='teamleader',
            table='TeamLeader',
        ),
        migrations.AlterModelTable(
            name='teammember',
            table='TeamMember',
        ),
    ]
