# Generated by Django 3.1.3 on 2022-11-04 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplusplusapp', '0020_auto_20221104_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='teamAffiliation',
        ),
        migrations.AddField(
            model_name='employee',
            name='teamAff',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='belongsTo', to='aplusplusapp.team'),
        ),
    ]
