# Generated by Django 3.1.3 on 2022-11-04 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplusplusapp', '0022_auto_20221104_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='teamAff',
        ),
    ]
