# Generated by Django 3.1.3 on 2022-11-04 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplusplusapp', '0025_auto_20221104_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='employee',
            table='employee',
        ),
        migrations.AlterModelTable(
            name='team',
            table='team',
        ),
        migrations.AlterModelTable(
            name='teamleader',
            table='teamLeader',
        ),
        migrations.AlterModelTable(
            name='teammember',
            table='teamMember',
        ),
    ]
