# Generated by Django 3.1.3 on 2022-11-04 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplusplusapp', '0028_auto_20221104_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='teamAff',
            new_name='teamAffiliation',
        ),
    ]
