# Generated by Django 3.1.3 on 2022-11-04 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplusplusapp', '0029_auto_20221104_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='teamAffiliation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='belongsTo', to='aplusplusapp.team'),
        ),
    ]
