# Generated by Django 3.1.3 on 2022-11-04 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplusplusapp', '0034_auto_20221104_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workarrangement',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
