# Generated by Django 3.1.3 on 2022-11-04 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplusplusapp', '0036_auto_20221104_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workarrangement',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workedBy', to='aplusplusapp.employee'),
        ),
    ]
