# Generated by Django 3.1.3 on 2022-11-04 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplusplusapp', '0040_auto_20221104_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='teamAffiliation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamAffiliation', to='aplusplusapp.team'),
        ),
        migrations.AlterField(
            model_name='workarrangement',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='aplusplusapp.employee'),
        ),
    ]
