# Generated by Django 3.1.3 on 2022-11-04 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplusplusapp', '0041_auto_20221104_1808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammember',
            old_name='team',
            new_name='teamOf',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='member',
        ),
        migrations.AlterField(
            model_name='teamleader',
            name='leader',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leader', to='aplusplusapp.team', to_field='teamTitle'),
        ),
    ]
