# Generated by Django 3.1.3 on 2022-11-04 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplusplusapp', '0043_auto_20221104_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='hourlyRate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='name',
            field=models.CharField(default='Max Mustermann', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='teamAffiliation',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='teamAffiliation', to='aplusplusapp.team'),
        ),
        migrations.AddField(
            model_name='team',
            name='teamTitle',
            field=models.CharField(default='unassigned', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='teamleader',
            name='leader',
            field=models.OneToOneField(default='none', on_delete=django.db.models.deletion.CASCADE, related_name='leader', to='aplusplusapp.team', to_field='teamTitle'),
        ),
        migrations.AddField(
            model_name='teamleader',
            name='team',
            field=models.ForeignKey(default='none', on_delete=django.db.models.deletion.CASCADE, to='aplusplusapp.team'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='team',
            field=models.ForeignKey(default='none', on_delete=django.db.models.deletion.CASCADE, to='aplusplusapp.team'),
        ),
        migrations.AddField(
            model_name='workarrangement',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='aplusplusapp.employee'),
        ),
        migrations.AddField(
            model_name='workarrangement',
            name='workTitle',
            field=models.CharField(default='Chillin', max_length=255),
        ),
        migrations.AddField(
            model_name='workarrangement',
            name='workedTime',
            field=models.CharField(choices=[('FT', 'Full Time'), ('PT', 'Part Time 100%'), ('PT75', 'Part Time 75%'), ('PT50', 'Part Time 50%'), ('PT25', 'Part Time 25%')], default='Full Time', max_length=255),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teamleader',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workarrangement',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='employee',
            table='employee',
        ),
        migrations.AlterModelTable(
            name='team',
            table='team',
        ),
        migrations.AlterModelTable(
            name='teamleader',
            table='teamLeader',
        ),
        migrations.AlterModelTable(
            name='teammember',
            table='teamMember',
        ),
        migrations.AlterModelTable(
            name='workarrangement',
            table='workArrangement',
        ),
    ]
