# Generated by Django 3.1.3 on 2022-11-04 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplusplusapp', '0044_auto_20221104_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='hourlyRate',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='teamAffiliation',
        ),
        migrations.RemoveField(
            model_name='team',
            name='teamTitle',
        ),
        migrations.RemoveField(
            model_name='teamleader',
            name='leader',
        ),
        migrations.RemoveField(
            model_name='teamleader',
            name='team',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='team',
        ),
        migrations.RemoveField(
            model_name='workarrangement',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='workarrangement',
            name='workTitle',
        ),
        migrations.RemoveField(
            model_name='workarrangement',
            name='workedTime',
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='team',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='teamleader',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='workarrangement',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterModelTable(
            name='employee',
            table=None,
        ),
        migrations.AlterModelTable(
            name='team',
            table=None,
        ),
        migrations.AlterModelTable(
            name='teamleader',
            table=None,
        ),
        migrations.AlterModelTable(
            name='teammember',
            table=None,
        ),
        migrations.AlterModelTable(
            name='workarrangement',
            table=None,
        ),
    ]
